---
# Dataset config

robot: "upkie_mpc"
path_to_dataset: "priors/upkie/upkie_Sep_27_2024_1157/dataset.hdf5"
pretrained_model_ckpt: null

gains_to_optimize: [0, 1]
thetas_randomized: [0, 1, 3]
metric_idxs: [0, 1, 2]
metric_idxs_to_invert: []
theta_noise_std: 0.0
metric_noise_std: 0.0
history_noise_std: 0.0
input_batch_idxs: [0, 4]
target_batch_idx: 3
traj_dim: 0
ref_track_per_term_scaling: False
ref_track_ds_factor: 1
params_type: "upkie_train"

# Training config
phase_1_method: "linear"
phase_2_method: "kf"
seeds: [11]
train_amt: 0.95
phase_1_lr: 1e-4
phase_2_lr: 1e-4
num_phase_1_iters: 50
num_phase_2_iters: 100
random_num_lstsq: True

# Encoder config
history_length: 0
history_latent_dim: 25
encoder_layer_sizes: [64, 64]
encoder_nonlin: "relu"

# history_length: 1
# history_latent_dim: 10
# encoder_layer_sizes: [64, 32]
# encoder_nonlin: "relu"


# Lstsq net config
n_bases: 3
layer_sizes: [32, 32]
nonlin: "relu"
